version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  vehicles-mgmt:
    build:
      context: ./vehicles-mgmt
      dockerfile: Dockerfile
    container_name: vehicles-mgmt
    ports:
      - "8081:8081"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/vehicle_db
      - SPRING_R2DBC_USERNAME=your_username  
      - SPRING_R2DBC_PASSWORD=your_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
