apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicles-mgmt
spec:
  replicas: 1  # Initial replica count
  selector:
    matchLabels:
      app: vehicles-mgmt
  template:
    metadata:
      labels:
        app: vehicles-mgmt
    spec:
      containers:
        - name: vehicles-mgmt
          image: kaiohenricunha/vehicles-mgmt:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:vehicle_db;DB_CLOSE_DELAY=-1
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicles-mgmt
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: vehicles-mgmt
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vehicles-mgmt-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehicles-mgmt
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
