spring:
  application:
    name: vehicles-mgmt
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vehicle_db
    password: your_password
  data:
    r2dbc:
      repositories:
        enabled: true
  webflux:
    base-path: /vehicles
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
