spring:
  application:
    name: vehicles-mgmt

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/vehicle_db  # Docker network connection
    username: your_username
    password: your_password

  data:
    r2dbc:
      repositories:
        enabled: true

  sql:
    init:
      mode: always  # This ensures the schema.sql is always applied on startup
      schema-locations: classpath:schema.sql

  webflux:
    base-path: /vehicles

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # Eureka server URL

server:
  port: 8081  # Service port

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
